name: gold247
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  clipboard: ^0.1.3
  flutter_bloc: ^8.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.1.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.8
  uuid: ^3.0.4
  font_awesome_flutter: ^9.1.0
  page_transition: ^2.0.4
  syncfusion_flutter_charts: ^19.2.62
  screen_loader: ^3.0.2
  loader_overlay: ^2.0.2+1
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.10
  razorpay_flutter: ^1.1.1
  sizer: ^2.0.10
  share: ^2.0.4
  video_player: ^2.2.3
  visibility_detector: ^0.2.0
  flutter_countdown_timer: ^4.1.0
  firebase_messaging: ^11.1.0
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  showcaseview: ^1.1.1
  tutorial_coach_mark: ^1.1.1
  shimmer: ^2.0.0
  flutter_local_notifications: ^9.0.1
  image_picker: ^0.8.4+1
  sms_autofill: ^2.2.0
  intl_phone_number_input: ^0.7.0+2
  otp_autofill: ^2.0.0
  top_snackbar_flutter: ^1.0.2
  another_flushbar: ^1.10.26
  just_audio: ^0.9.18
  scroll_to_index: ^2.1.1
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/splash.mp3
    - assets/icon/
    - assets/icon/primary-color/
    - assets/icon/grey/
    - assets/user/
    - assets/crypto_icon/
    - assets/Logo.png
    - assets/crypto_icon/gold_ingots.png
    - assets/gif_file/GIF_Med.gif


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
    - family: Jost
      fonts:
        - asset: fonts/Jost/Jost-Regular.ttf
        - asset: fonts/Jost/Jost-Medium.ttf
          weight: 500
        - asset: fonts/Jost/Jost-Bold.ttf
          weight: 700